FROM ubuntu:18.04

ARG USER=devuser
ENV USER=${USER}
ENV HOME=/home/${USER}

ENV TZ=UTC

# Install sudo
RUN apt-get update && apt-get upgrade -y && apt-get install -y sudo

# Add non-root user
RUN addgroup --gid 1000 ${USER}
RUN adduser --gecos "" --uid 1000 --gid 1000 ${USER}
RUN echo "${USER}:${USER}" | chpasswd

# Add user to sudoers
RUN echo "$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Switch to user
USER ${USER}

# Install dev stuff
RUN DEBIAN_FRONTEND=noninteractive sudo apt-get install -y build-essential gcc g++ gdb clang make \
    ninja-build cmake autoconf automake locales-all dos2unix rsync \
    tar python python3 git iproute2 inetutils-ping dnsutils

