FROM ubuntu:24.04

ARG USER=ubuntu
ENV USER=ubuntu
ENV HOME=/home/ubuntu

ENV TZ=UTC

# Install sudo
RUN apt-get update && apt-get upgrade -y && apt-get install -y sudo

# Add user to sudoers
RUN echo "$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Switch to user
USER ${USER}

# Install dev stuff
RUN DEBIAN_FRONTEND=noninteractive sudo apt-get install -y build-essential gcc g++ gdb clang make \
    ninja-build cmake autoconf automake locales-all dos2unix rsync \
    tar python3 git iproute2 inetutils-ping bind9-dnsutils

