FROM ubuntu/mysql:8.0-20.04_beta

ARG USER=devuser
ENV USER=${USER}
ENV HOME=/home/${USER}

ENV TZ=UTC

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        build-essential gcc g++ gdb clang make \
        cmake ninja-build autoconf automake \
        locales-all dos2unix rsync tar python3 \
        git iproute2 inetutils-ping bind9-dnsutils

