FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive
ENV DEBIAN_FRONTEND noninteractive

# Install sudo
RUN apt-get update && apt-get upgrade -y && apt-get install -y sudo

# Add non-root user
RUN addgroup --gid 1000 devuser
RUN adduser --gecos "" --uid 1000 --gid 1000 devuser
RUN echo 'devuser:devuser' | chpasswd

# Add user HOME and USER environment variables
ENV HOME /home/devuser
ENV USER devuser

# Add user to sudoers
RUN echo "$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Install def stuff
RUN sudo apt-get install -y build-essential gcc g++ gdb clang make \
    ninja-build cmake autoconf automake locales-all dos2unix rsync \
    tar python python3 git vim iproute2 inetutils-ping dnsutils

