FROM umtdg/xenial-16.04:latest

# Install developer tools and some utilization packages
RUN sudo apt-get install -y build-essential gcc g++ gdb clang make \
    ninja-build cmake autoconf automake locales-all \
    dos2unix rsync tar python git

