FROM umtdg/ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
ENV DEBIAN_FRONTEND noninteractive

# Install developer tools and some utilization packages
RUN sudo apt-get install -y build-essential gcc g++ gdb clang make \
    ninja-build cmake autoconf automake locales-all dos2unix rsync \
    tar python3 git vim iproute2 inetutils-ping bind9-dnsutils
