name: Ubuntu 22.04

on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - .github/workflows/ubuntu-22.04.yaml
      - .github/workflows/build.yaml
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  ubuntu:
    secrets: inherit
    uses: ./.github/workflows/build.yaml
    with:
      dockerfile: ./Dockerfile.22.04
      image: ubuntu:22.04
      base_image: ubuntu:22.04
