name: Ubuntu 24.04

on:
  push:
    branches:
      - master
    paths:
      - Dockerfile.24.04
      - .github/workflows/ubuntu-24.04.yaml
      - .github/workflows/build.yaml
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  ubuntu:
    secrets: inherit
    uses: ./.github/workflows/build.yaml
    with:
      dockerfile: ./Dockerfile.24.04
      image: ubuntu:24.04
